// <auto-generated />
using InstruktorerPassAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InstruktorerPassAPI.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InstruktorerPassAPI.Models.Instruktorer", b =>
                {
                    b.Property<int>("In_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("In_Adress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Epost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Fornamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Mobil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("In_Personnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("In_Postnummer")
                        .HasColumnType("int");

                    b.HasKey("In_Id");

                    b.ToTable("Instruktorer");
                });

            modelBuilder.Entity("InstruktorerPassAPI.Models.InstruktorerPass", b =>
                {
                    b.Property<int>("IP_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IP_InstruktorId")
                        .HasColumnType("int");

                    b.Property<int>("IP_PassId")
                        .HasColumnType("int");

                    b.HasKey("IP_Id");

                    b.ToTable("InstruktorerPass");
                });

            modelBuilder.Entity("InstruktorerPassAPI.Models.Pass", b =>
                {
                    b.Property<int>("Pa_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Pa_Aktivitet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Pa_Id");

                    b.ToTable("Pass");
                });
#pragma warning restore 612, 618
        }
    }
}
